# Generated by Django 4.0.1 on 2022-01-10 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='post_date',
            new_name='update_date',
        ),
    ]
